spring.application.name=student-api

# PostgreSQL
spring.datasource.url=jdbc:postgresql://pgdb-rw.db-1.svc.cluster.local:5432/pgdb
spring.datasource.username=admin_pgdb
spring.datasource.password=5lj9NKvx&cNdEDyY0#o9ZYX78XhP*6kZ
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Context path
server.servlet.context-path=/api
server.port=8080
